TJD: One additional library needed for some Cygwin installs.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12175,6 +12175,65 @@ echo "$as_me: error: Unable to find wsock32 libraries!" >&2;}
    { (exit 1); exit 1; }; }
       fi
       ;;
+   cygwin*)
+      echo "$as_me:$LINENO: checking for main in -lrpclib" >&5
+echo $ECHO_N "checking for main in -lrpclib... $ECHO_C" >&6
+if test "${ac_cv_lib_rpclib_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrpclib  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_rpclib_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_rpclib_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_rpclib_main" >&5
+echo "${ECHO_T}$ac_cv_lib_rpclib_main" >&6
+if test $ac_cv_lib_rpclib_main = yes; then
+  rpc_found="yes"
+else
+  rpc_found=""
+fi
+
+      if test -n "${rpc_found}"; then
+           socket_lib="-lrpclib"
+      fi
+      ;;
 esac
 echo "$as_me:$LINENO: result: ------------- end processing APBS configure options -----------" >&5
 echo "${ECHO_T}------------- end processing APBS configure options -----------" >&6
