MORE AUTOCONF CRAP

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9176,16 +9176,22 @@ CPPFLAGS_SAVE=${CPPFLAGS};
 LDFLAGS=${maloc_lib_path};
 CPPFLAGS=${maloc_inc_path};
 maloc_found="";
-echo "$as_me:$LINENO: checking for maloc/maloc.h" >&5
+if test "${ac_cv_header_maloc_maloc_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for maloc/maloc.h" >&5
 echo $ECHO_N "checking for maloc/maloc.h... $ECHO_C" >&6
 if test "${ac_cv_header_maloc_maloc_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_maloc_maloc_h" >&5
+echo "${ECHO_T}$ac_cv_header_maloc_maloc_h" >&6
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking maloc/maloc.h usability" >&5
+echo $ECHO_N "checking maloc/maloc.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
-${maloc_inc_path}
-
+$ac_includes_default
 #include <maloc/maloc.h>
 _ACEOF
 rm -f conftest.$ac_objext
@@ -9200,16 +9206,77 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_header_maloc_maloc_h=yes
+  ac_header_compiler=yes
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-ac_cv_header_maloc_maloc_h=no
+ac_header_compiler=no
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking maloc/maloc.h presence" >&5
+echo $ECHO_N "checking maloc/maloc.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <maloc/maloc.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: maloc/maloc.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: maloc/maloc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: maloc/maloc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: maloc/maloc.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: maloc/maloc.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: maloc/maloc.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: maloc/maloc.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: maloc/maloc.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: maloc/maloc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: maloc/maloc.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for maloc/maloc.h" >&5
+echo $ECHO_N "checking for maloc/maloc.h... $ECHO_C" >&6
+if test "${ac_cv_header_maloc_maloc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_maloc_maloc_h=$ac_header_preproc
 fi
 echo "$as_me:$LINENO: result: $ac_cv_header_maloc_maloc_h" >&5
 echo "${ECHO_T}$ac_cv_header_maloc_maloc_h" >&6
+
+fi
 if test $ac_cv_header_maloc_maloc_h = yes; then
   maloc_found="yes";maloc_inc="${maloc_inc_path}"
 else
@@ -9224,8 +9291,7 @@ if test "${ac_cv_lib_maloc_maloc_link+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmaloc ${maloc_lib_path}-lmaloc ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib}
-${nsl_lib} ${math_lib} $LIBS"
+LIBS="-lmaloc ${maloc_lib_path}-lmaloc ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -9404,16 +9470,22 @@ fi;
     LDFLAGS=${mpi_lib_path} ${nsl_lib} ${socket_lib};
     CPPFLAGS=${mpi_inc_path};
     mpi_use="";
-    echo "$as_me:$LINENO: checking for mpi.h" >&5
+    if test "${ac_cv_header_mpi_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for mpi.h" >&5
 echo $ECHO_N "checking for mpi.h... $ECHO_C" >&6
 if test "${ac_cv_header_mpi_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_mpi_h" >&5
+echo "${ECHO_T}$ac_cv_header_mpi_h" >&6
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking mpi.h usability" >&5
+echo $ECHO_N "checking mpi.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
-${mpi_inc_path}
-
+$ac_includes_default
 #include <mpi.h>
 _ACEOF
 rm -f conftest.$ac_objext
@@ -9428,16 +9500,77 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_header_mpi_h=yes
+  ac_header_compiler=yes
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-ac_cv_header_mpi_h=no
+ac_header_compiler=no
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking mpi.h presence" >&5
+echo $ECHO_N "checking mpi.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <mpi.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: mpi.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: mpi.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpi.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mpi.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: mpi.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: mpi.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpi.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: mpi.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mpi.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mpi.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for mpi.h" >&5
+echo $ECHO_N "checking for mpi.h... $ECHO_C" >&6
+if test "${ac_cv_header_mpi_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_mpi_h=$ac_header_preproc
 fi
 echo "$as_me:$LINENO: result: $ac_cv_header_mpi_h" >&5
 echo "${ECHO_T}$ac_cv_header_mpi_h" >&6
+
+fi
 if test $ac_cv_header_mpi_h = yes; then
   mpi_use="yes";mpi_inc="${mpi_inc_path}"
 else
@@ -9903,16 +10036,22 @@ echo "$as_me: checking for FEtk libraries and headers......" >&6;}
     LDFLAGS=${mc_lib_path};
     CPPFLAGS=${mc_inc_path};
     mc_found="";
-    echo "$as_me:$LINENO: checking for mc/mc.h" >&5
+    if test "${ac_cv_header_mc_mc_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for mc/mc.h" >&5
 echo $ECHO_N "checking for mc/mc.h... $ECHO_C" >&6
 if test "${ac_cv_header_mc_mc_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_mc_mc_h" >&5
+echo "${ECHO_T}$ac_cv_header_mc_mc_h" >&6
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking mc/mc.h usability" >&5
+echo $ECHO_N "checking mc/mc.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
-${mc_inc_path}
-
+$ac_includes_default
 #include <mc/mc.h>
 _ACEOF
 rm -f conftest.$ac_objext
@@ -9927,16 +10066,77 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_header_mc_mc_h=yes
+  ac_header_compiler=yes
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-ac_cv_header_mc_mc_h=no
+ac_header_compiler=no
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking mc/mc.h presence" >&5
+echo $ECHO_N "checking mc/mc.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <mc/mc.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: mc/mc.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: mc/mc.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mc/mc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mc/mc.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: mc/mc.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: mc/mc.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mc/mc.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: mc/mc.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: mc/mc.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: mc/mc.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for mc/mc.h" >&5
+echo $ECHO_N "checking for mc/mc.h... $ECHO_C" >&6
+if test "${ac_cv_header_mc_mc_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_mc_mc_h=$ac_header_preproc
 fi
 echo "$as_me:$LINENO: result: $ac_cv_header_mc_mc_h" >&5
 echo "${ECHO_T}$ac_cv_header_mc_mc_h" >&6
+
+fi
 if test $ac_cv_header_mc_mc_h = yes; then
   mc_found="yes";mc_inc="${mc_inc_path}"
 else
