Working version of APBS Opal command line tool

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -896,6 +896,7 @@ PY_LINKFLAGS
 PY_CC
 PY_PRESENT_TRUE
 PY_PRESENT_FALSE
+SITEPKGS
 apbs_do_maloc
 rl_lib
 mcx_lib
@@ -1544,6 +1545,7 @@ Optional Packages:
   --with-mpich2=PATH      toplevel MPICH2 directory
   --with-lam=PATH         toplevel LAM-MPI directory
   --with-openmpi          enable OpenMPI compilation
+  --with-python=PYTHONPATH           Specify python location.
   --with-blas=LDFLAGS     link to user-specified BLAS (specify flags to pass
                           to ld)
 
@@ -6467,7 +6469,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6470 "configure"' > conftest.$ac_ext
+  echo '#line 6472 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8236,11 +8238,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8239: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8241: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8243: \$? = $ac_status" >&5
+   echo "$as_me:8245: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8504,11 +8506,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8507: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8509: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8511: \$? = $ac_status" >&5
+   echo "$as_me:8513: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8608,11 +8610,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8611: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8613: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8615: \$? = $ac_status" >&5
+   echo "$as_me:8617: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10916,7 +10918,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10919 "configure"
+#line 10921 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11016,7 +11018,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11019 "configure"
+#line 11021 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13352,11 +13354,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13355: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13357: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13359: \$? = $ac_status" >&5
+   echo "$as_me:13361: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13456,11 +13458,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13459: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13461: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13463: \$? = $ac_status" >&5
+   echo "$as_me:13465: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15026,11 +15028,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15029: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15031: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15033: \$? = $ac_status" >&5
+   echo "$as_me:15035: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15130,11 +15132,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15133: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15135: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15137: \$? = $ac_status" >&5
+   echo "$as_me:15139: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17328,11 +17330,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17331: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17333: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17335: \$? = $ac_status" >&5
+   echo "$as_me:17337: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17596,11 +17598,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17599: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17603: \$? = $ac_status" >&5
+   echo "$as_me:17605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17700,11 +17702,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17703: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17705: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17707: \$? = $ac_status" >&5
+   echo "$as_me:17709: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22223,6 +22225,76 @@ else
 fi
 
 
+
+
+# Check whether --with-python was given.
+if test "${with_python+set}" = set; then
+  withval=$with_python; PYTHONPATH=$withval
+else
+  PYTHONPATH=""
+fi
+
+
+if test "$PYTHONPATH" = "" ; then
+  # Extract the first word of "python", so it can be a program name with args.
+set dummy python; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_py_path+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $py_path in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_py_path="$py_path" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_py_path="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+py_path=$ac_cv_path_py_path
+if test -n "$py_path"; then
+  { echo "$as_me:$LINENO: result: $py_path" >&5
+echo "${ECHO_T}$py_path" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  if test -z "${py_path}"; then
+	 { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+     { { echo "$as_me:$LINENO: error: Unable to find python!  Python location can be specified with --with-python" >&5
+echo "$as_me: error: Unable to find python!  Python location can be specified with --with-python" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+else
+  py_path=$PYTHONPATH
+fi
+
+PY_VERSION=`$py_path -c 'import sys; print sys.version[:3]'`
+SITEPKGS=${prefix}/lib/python${PY_VERSION}/site-packages
+sed -e 's%@SITEPKGS@%'${SITEPKGS}'%' ${top_apbsdir}/contrib/opal/ApbsClient.py.in > ${top_apbsdir}/contrib/opal/ApbsClient.py
+chmod 755 ${top_apbsdir}/contrib/opal/ApbsClient.py
+
+SITEPKGS=$SITEPKGS
+
+
 if test -z "${USE_FETK}";  then
 	{ echo "$as_me:$LINENO: checking for --disable-maloc-rebuild" >&5
 echo $ECHO_N "checking for --disable-maloc-rebuild... $ECHO_C" >&6; }
@@ -23729,7 +23801,7 @@ fi
 
 
 
-ac_config_files="$ac_config_files Makefile contrib/Makefile contrib/blas/Makefile contrib/pmgZ/Makefile contrib/aqua/Makefile tools/Makefile tools/mesh/Makefile tools/manip/Makefile tools/python/Makefile tools/arpack/Makefile tools/python/vgrid/Makefile src/Makefile src/generic/Makefile src/mg/Makefile src/fem/Makefile src/aaa_inc/Makefile src/aaa_inc/apbs/Makefile src/aaa_lib/Makefile examples/Makefile examples/actin-dimer/Makefile examples/alkanes/Makefile examples/born/Makefile examples/FKBP/Makefile examples/hca-bind/Makefile examples/ion-pmf/Makefile examples/ion-protein/Makefile examples/ionize/Makefile examples/pka-lig/Makefile examples/point-pmf/Makefile examples/protein-rna/Makefile examples/smpbe/Makefile examples/solv/Makefile bin/Makefile"
+ac_config_files="$ac_config_files Makefile contrib/Makefile contrib/blas/Makefile contrib/pmgZ/Makefile contrib/aqua/Makefile contrib/opal/Makefile contrib/opal/ZSI/Makefile tools/Makefile tools/mesh/Makefile tools/manip/Makefile tools/python/Makefile tools/arpack/Makefile tools/python/vgrid/Makefile src/Makefile src/generic/Makefile src/mg/Makefile src/fem/Makefile src/aaa_inc/Makefile src/aaa_inc/apbs/Makefile src/aaa_lib/Makefile examples/Makefile examples/actin-dimer/Makefile examples/alkanes/Makefile examples/born/Makefile examples/FKBP/Makefile examples/hca-bind/Makefile examples/ion-pmf/Makefile examples/ion-protein/Makefile examples/ionize/Makefile examples/pka-lig/Makefile examples/point-pmf/Makefile examples/protein-rna/Makefile examples/smpbe/Makefile examples/solv/Makefile bin/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -24343,6 +24415,8 @@ do
     "contrib/blas/Makefile") CONFIG_FILES="$CONFIG_FILES contrib/blas/Makefile" ;;
     "contrib/pmgZ/Makefile") CONFIG_FILES="$CONFIG_FILES contrib/pmgZ/Makefile" ;;
     "contrib/aqua/Makefile") CONFIG_FILES="$CONFIG_FILES contrib/aqua/Makefile" ;;
+    "contrib/opal/Makefile") CONFIG_FILES="$CONFIG_FILES contrib/opal/Makefile" ;;
+    "contrib/opal/ZSI/Makefile") CONFIG_FILES="$CONFIG_FILES contrib/opal/ZSI/Makefile" ;;
     "tools/Makefile") CONFIG_FILES="$CONFIG_FILES tools/Makefile" ;;
     "tools/mesh/Makefile") CONFIG_FILES="$CONFIG_FILES tools/mesh/Makefile" ;;
     "tools/manip/Makefile") CONFIG_FILES="$CONFIG_FILES tools/manip/Makefile" ;;
@@ -24601,6 +24675,7 @@ PY_LINKFLAGS!$PY_LINKFLAGS$ac_delim
 PY_CC!$PY_CC$ac_delim
 PY_PRESENT_TRUE!$PY_PRESENT_TRUE$ac_delim
 PY_PRESENT_FALSE!$PY_PRESENT_FALSE$ac_delim
+SITEPKGS!$SITEPKGS$ac_delim
 apbs_do_maloc!$apbs_do_maloc$ac_delim
 rl_lib!$rl_lib$ac_delim
 mcx_lib!$mcx_lib$ac_delim
@@ -24624,7 +24699,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 51; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 52; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
