Added the --enable-python flag.  Python wrappers are now disabled by default, but can be enabled for untested systems if the user desires.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1039,6 +1039,7 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-install-triplet
                           disable OS version specific installation
+  --enable-python         enables Python wrapper compilation
   --disable-fetk          disable FEtk features
   --enable-pansi          enable pedantic ANSI compilation
   --disable-tools         disable tool compilation
@@ -4565,7 +4566,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4568:" \
+echo "$as_me:4569:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5912,7 +5913,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5915 "configure"' > conftest.$ac_ext
+  echo '#line 5916 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7655,11 +7656,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7658: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7662: \$? = $ac_status" >&5
+   echo "$as_me:7663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7917,11 +7918,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7920: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7921: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7924: \$? = $ac_status" >&5
+   echo "$as_me:7925: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7979,11 +7980,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7982: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7986: \$? = $ac_status" >&5
+   echo "$as_me:7987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9364,7 +9365,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 9367 "configure"' > conftest.$ac_ext
+    echo '#line 9368 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10235,7 +10236,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10238 "configure"
+#line 10239 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10333,7 +10334,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10336 "configure"
+#line 10337 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12581,11 +12582,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12584: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12585: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12588: \$? = $ac_status" >&5
+   echo "$as_me:12589: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12643,11 +12644,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12646: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12647: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12650: \$? = $ac_status" >&5
+   echo "$as_me:12651: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13158,7 +13159,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 13161 "configure"' > conftest.$ac_ext
+    echo '#line 13162 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -14029,7 +14030,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14032 "configure"
+#line 14033 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14127,7 +14128,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14130 "configure"
+#line 14131 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15012,11 +15013,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15015: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15019: \$? = $ac_status" >&5
+   echo "$as_me:15020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15074,11 +15075,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15077: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15078: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15081: \$? = $ac_status" >&5
+   echo "$as_me:15082: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16439,7 +16440,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 16442 "configure"' > conftest.$ac_ext
+    echo '#line 16443 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -17212,11 +17213,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17215: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17216: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17219: \$? = $ac_status" >&5
+   echo "$as_me:17220: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17474,11 +17475,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17477: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17478: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17481: \$? = $ac_status" >&5
+   echo "$as_me:17482: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17536,11 +17537,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17539: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17540: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17543: \$? = $ac_status" >&5
+   echo "$as_me:17544: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18921,7 +18922,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 18924 "configure"' > conftest.$ac_ext
+    echo '#line 18925 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -19792,7 +19793,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19795 "configure"
+#line 19796 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19890,7 +19891,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19893 "configure"
+#line 19894 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23270,8 +23271,22 @@ echo "${ECHO_T}---------- end configuring for MALOC linkage --------------" >&6
 
 echo "$as_me:$LINENO: result: ---------- begin configuring for Python wrappers --------------" >&5
 echo "${ECHO_T}---------- begin configuring for Python wrappers --------------" >&6
+echo "$as_me:$LINENO: checking for --enable-python" >&5
+echo $ECHO_N "checking for --enable-python... $ECHO_C" >&6
+# Check whether --enable-python or --disable-python was given.
+if test "${enable_python+set}" = set; then
+  enableval="$enable_python"
+   with_python="yes"
+else
+   with_python=""
 
-# Extract the first word of "python", so it can be a program name with args.
+fi;
+
+PY_ENABLE=""
+if test -n "${with_python}"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    # Extract the first word of "python", so it can be a program name with args.
 set dummy python; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -23310,60 +23325,55 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test -n "${py_path}"; then
-      PY_VERSION=`$py_path -c 'import sys; print sys.version[:3]'`
-      PY_PREFIX=`$py_path -c 'import sys; print sys.prefix'`
-   PY_EXEC_PREFIX=`$py_path -c 'import sys; print sys.exec_prefix'`
-   if test -f $PY_PREFIX/include/python$PY_VERSION/Python.h; then
-      PY_CFLAGS="-I$PY_PREFIX/include/python$PY_VERSION -I$PY_EXEC_PREFIX/include/python$PY_VERSION"
-   else
-	  PY_CFLAGS=""
-   fi
-else
-   PY_CFLAGS=""
-fi
+    PY_ENABLE="yes"
 
-PY_LINKFLAGS=${CFLAGS}
-PY_CC=${CC}
+    if test -n "${py_path}"; then
+              PY_VERSION=`$py_path -c 'import sys; print sys.version[:3]'`
+              PY_PREFIX=`$py_path -c 'import sys; print sys.prefix'`
+       PY_EXEC_PREFIX=`$py_path -c 'import sys; print sys.exec_prefix'`
+       if test -f $PY_PREFIX/include/python$PY_VERSION/Python.h; then
+          PY_CFLAGS="-I$PY_PREFIX/include/python$PY_VERSION -I$PY_EXEC_PREFIX/include/python$PY_VERSION"
+       fi
+    fi
 
-PY_LDFLAGS=""
-PY_SHARED=""
-case $host_os in
-   linux*)
-      PY_SHARED="-shared";;
-   irix*)
-      PY_SHARED="-shared"
-      PY_LDFLAGS="-lftn -lm";;
-   sun|solaris**)
-      PY_SHARED="-G"
-      PY_LDFLAGS="-lF77 -lm -lM77 -lsunmath"
-      PY_CFLAGS="";;
-   cygwin|mingw32|windows**)
-      PY_CFLAGS="";;
-   darwin**)
-      PY_CC=${F77}
-      PY_LINKFLAGS="-Wl,-framework -Wl,Python -bundle";;
-   *)
-      PY_CFLAGS="";;
-esac
+    PY_LINKFLAGS=${CFLAGS}
+    PY_CC=${CC}
 
 
-IS_STATIC=`echo ${LDFLAGS} | grep static`
-case $host_cpu in
-   x86_64*)
-      if test "${F77}" = "pgf77"; then
-	  PY_CC=${F77}
-      else
-	  PY_CFLAGS=""
-      fi
-      if test -n "${IS_STATIC}"; then
-	  PY_CFLAGS=""
-      fi;;
-   powerpc64*)
-      PY_CFLAGS="";;
-   i*86)
-      if test "${CC}" = "icc"; then
-          echo "$as_me:$LINENO: checking for d_int_val in -lifcore_pic" >&5
+    PY_LDFLAGS=""
+    PY_SHARED=""
+    case $host_os in
+       linux*)
+           PY_SHARED="-shared";;
+       irix*)
+           PY_SHARED="-shared"
+           PY_LDFLAGS="-lftn -lm";;
+       sun|solaris**)
+           PY_SHARED="-G"
+           PY_LDFLAGS="-lF77 -lm -lM77 -lsunmath";;
+       darwin**)
+           PY_CC=${F77}
+           PY_LINKFLAGS="-Wl,-framework -Wl,Python -bundle";;
+       mingw*)
+           PY_PREFIX=`$py_path -c 'import sys, string; a=sys.prefix; b=string.replace(a,"c:\\\","/c/"); print b;'`
+           PY_EXEC_PREFIX=`$py_path -c 'import sys, string; a=sys.exec_prefix; b=string.replace(a,"c:\\\","/c/"); print b;'`
+                      PY_NOSPACE_VER=`$py_path -c 'import sys; a=sys.version[0]; b=sys.version[2]; print a+b;'`
+                      PY_CC=${F77}
+           PY_LDFLAGS="-L$PY_PREFIX/libs -lpython$PY_NOSPACE_VER"
+           PY_SHARED="-shared"
+           if test -f $PY_PREFIX/include/Python.h; then
+               PY_CFLAGS="-I$PY_PREFIX/include -I$PY_EXEC_PREFIX/include"
+           fi;;
+    esac
+
+
+    IS_STATIC=`echo ${LDFLAGS} | grep static`
+    case $host_cpu in
+       x86_64*)
+          PY_CC=${F77};;
+       i*86)
+          if test "${CC}" = "icc"; then
+             echo "$as_me:$LINENO: checking for d_int_val in -lifcore_pic" >&5
 echo $ECHO_N "checking for d_int_val in -lifcore_pic... $ECHO_C" >&6
 if test "${ac_cv_lib_ifcore_pic_d_int_val+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -23433,25 +23443,19 @@ else
   ifcore_lib=""
 fi
 
-	      if test -n "${ifcore_lib}"; then
-	          PY_LDFLAGS=${ifcore_lib}
-	      else
-	          PY_CFLAGS=""
-	      fi
-	      if test -n "${IS_STATIC}"; then
-	          PY_LINKFLAGS="$CFLAGS -static-libcxa -Wl,-static"
-          fi
-      else
-          if test "$CC" != "gcc"; then
-              PY_CFLAGS=""
-          fi
-      fi;;
-   ia64*)
-      if test -n "${mpi_use}"; then
-          PY_CFLAGS=""
-      fi
-      if test "${CC}" = "icc"; then
-          echo "$as_me:$LINENO: checking for d_int_val in -lifcore_pic" >&5
+             if test -n "${ifcore_lib}"; then
+	            PY_LDFLAGS=${ifcore_lib}
+	         else
+                echo "$as_me:$LINENO: result: \"WARNING: Unable to find Intel's ifcore_pic library - Python wrappers may fail looking for d_int_val.\"" >&5
+echo "${ECHO_T}\"WARNING: Unable to find Intel's ifcore_pic library - Python wrappers may fail looking for d_int_val.\"" >&6
+	         fi
+	         if test -n "${IS_STATIC}"; then
+	            PY_LINKFLAGS="$CFLAGS -static-libcxa -Wl,-static"
+             fi
+          fi;;
+       ia64*)
+          if test "${CC}" = "icc"; then
+             echo "$as_me:$LINENO: checking for d_int_val in -lifcore_pic" >&5
 echo $ECHO_N "checking for d_int_val in -lifcore_pic... $ECHO_C" >&6
 if test "${ac_cv_lib_ifcore_pic_d_int_val+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -23521,24 +23525,30 @@ else
   ifcore_lib=""
 fi
 
-	      if test -n "${ifcore_lib}"; then
-	          PY_LDFLAGS=${ifcore_lib}
-	      else
-	          PY_CFLAGS=""
-	      fi
-	      if test -n "${IS_STATIC}"; then
-	          if (test -f /usr/lib/libc.so) && (test -f /usr/lib/libm.so); then
-	              PY_LINKFLAGS="$CFLAGS -static-libcxa -Wl,-static,/usr/lib/libc.so,/usr/lib/libm.so"
-	          else
-                      PY_CFLAGS=""
-	          fi
-          fi
-      else
-          PY_CFLAGS=""
-      fi
-esac
+	         if test -n "${ifcore_lib}"; then
+	            PY_LDFLAGS=${ifcore_lib}
+	         else
+	           	echo "$as_me:$LINENO: result: \"WARNING: Unable to find Intel's ifcore_pic library - Python wrappers may fail looking for d_int_val.\"" >&5
+echo "${ECHO_T}\"WARNING: Unable to find Intel's ifcore_pic library - Python wrappers may fail looking for d_int_val.\"" >&6
+	         fi
+	         if test -n "${IS_STATIC}"; then
+	             if (test -f /usr/lib/libc.so) && (test -f /usr/lib/libm.so); then
+	                PY_LINKFLAGS="$CFLAGS -static-libcxa -Wl,-static,/usr/lib/libc.so,/usr/lib/libm.so"
+	             else
+                    echo "$as_me:$LINENO: result: \"WARNING:  Could not find libc.so or libm.so in /usr/lib\"" >&5
+echo "${ECHO_T}\"WARNING:  Could not find libc.so or libm.so in /usr/lib\"" >&6
+	             fi
+             fi
+         fi;;
+   esac
 
-if test -n "${PY_CFLAGS}"; then
+else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+if test -n "${PY_ENABLE}"; then
    echo "$as_me:$LINENO: result: Python wrappers enabled" >&5
 echo "${ECHO_T}Python wrappers enabled" >&6
 else
@@ -23558,7 +23568,7 @@ PY_CC=$PY_CC
 
 
 
-if test -n "${PY_CFLAGS}"; then
+if test -n "${PY_ENABLE}"; then
   PY_PRESENT_TRUE=
   PY_PRESENT_FALSE='#'
 else
@@ -23568,7 +23578,6 @@ fi
 
 echo "$as_me:$LINENO: result: ---------- end configuring for Python wrappers --------------" >&5
 echo "${ECHO_T}---------- end configuring for Python wrappers --------------" >&6
-
 
 echo "$as_me:$LINENO: result: ---------- begin configuring for FEtk linkage --------------" >&5
 echo "${ECHO_T}---------- begin configuring for FEtk linkage --------------" >&6
