TJD:  Python wrappers now part of of configure script for ia64 architecture

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -469,7 +469,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os fetk_cpu_vendor_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE APBS_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 CPP LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL py_path PY_SHARED PY_LDEXTRA PY_CFLAGS PY_PRESENT_TRUE PY_PRESENT_FALSE math_lib liberty_lib nsl_lib socket_lib thread_lib maloc_lib maloc_inc mpi_lib mpi_inc mpi_bin rl_lib mcx_lib mcx_inc mc_lib mc_inc wall wall_pedantic wall_pedantic_ansi pedantic_ansi apbs_do_tools blas_lib UHBD_COMPILE_TRUE UHBD_COMPILE_FALSE arpack_lib arpack_do_tools tree_lib lib_list inc_list LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os fetk_cpu_vendor_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE APBS_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 CPP LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL py_path PY_SHARED PY_LDFLAGS PY_CFLAGS PY_LINKFLAGS PY_PRESENT_TRUE PY_PRESENT_FALSE math_lib liberty_lib nsl_lib socket_lib thread_lib maloc_lib maloc_inc mpi_lib mpi_inc mpi_bin rl_lib mcx_lib mcx_inc mc_lib mc_inc wall wall_pedantic wall_pedantic_ansi pedantic_ansi apbs_do_tools blas_lib UHBD_COMPILE_TRUE UHBD_COMPILE_FALSE arpack_lib arpack_do_tools tree_lib lib_list inc_list LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -8980,17 +8980,18 @@ else
    PY_CFLAGS=""
 fi
 
-PY_LDEXTRA=""
+PY_LDFLAGS=""
 PY_SHARED=""
+PY_LINKFLAGS=""
 case $host_os in
    linux*)
       PY_SHARED="-shared";;
    irix*)
       PY_SHARED="-shared"
-      PY_LDEXTRA="-lftn -lm";;
+      PY_LDFLAGS="-lftn -lm";;
    sun|solaris**)
       PY_SHARED="-G"
-      PY_LDEXTRA="-lF77 -lm -lM77 -lsunmath";;
+      PY_LDFLAGS="-lF77 -lm -lM77 -lsunmath";;
    cygwin|mingw32|windows**)
       PY_CFLAGS="";;
    *)
@@ -9001,13 +9002,94 @@ case $host_cpu in
       PY_CFLAGS="";;
    powerpc64*)
       PY_CFLAGS="";;
+   ia64*)
+      PY_LINKFLAGS=${CFLAGS}
+      IS_STATIC=`echo ${LDFLAGS} | grep static-libcxa`
+      if test "${CC}" = "icc"; then
+          echo "$as_me:$LINENO: checking for d_int_val in -lifcore_pic" >&5
+echo $ECHO_N "checking for d_int_val in -lifcore_pic... $ECHO_C" >&6
+if test "${ac_cv_lib_ifcore_pic_d_int_val+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lifcore_pic  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char d_int_val ();
+int
+main ()
+{
+d_int_val ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ifcore_pic_d_int_val=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ifcore_pic_d_int_val=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ifcore_pic_d_int_val" >&5
+echo "${ECHO_T}$ac_cv_lib_ifcore_pic_d_int_val" >&6
+if test $ac_cv_lib_ifcore_pic_d_int_val = yes; then
+  ifcore_lib="-lifcore_pic"
+else
+  ifcore_lib=""
+fi
+
+	  if test -n "${ifcore_lib}"; then
+	      PY_LDFLAGS=${ifcore_lib}
+	  else
+	      PY_CFLAGS=""
+	  fi
+	  if test -n "${IS_STATIC}"; then
+	      if (test -f /usr/lib/libc.so) && (test -f /usr/lib/libm.so); then
+	          PY_LINKFLAGS="$CFLAGS -static-libcxa -Wl,-static,/usr/lib/libc.so,/usr/lib/libm.so"
+	      else
+                  PY_CFLAGS=""
+	      fi
+          fi
+      else
+          PY_CFLAGS=""
+      fi
 esac
 
 PY_SHARED=$PY_SHARED
 
-PY_LDEXTRA=$PY_LDEXTRA
+PY_LDFLAGS=$PY_LDFLAGS
 
 PY_CFLAGS=$PY_CFLAGS
+
+PY_LINKFLAGS=$PY_LINKFLAGS
 
 
 
@@ -10115,7 +10197,6 @@ CPPFLAGS=${CPPFLAGS_SAVE};
 
 
 
-
 LDFLAGS_SAVE=${LDFLAGS};
 CPPFLAGS_SAVE=${CPPFLAGS};
 LDFLAGS=${maloc_lib_path};
@@ -10603,7 +10684,7 @@ echo "${ECHO_T}no" >&6
         rl_lib_path="";
     fi
 
-        LDFLAGS_SAVE=${LDFLAGS};
+
     LDFLAGS=${rl_lib_path};
     echo "$as_me:$LINENO: checking for tgetnum in -lncurses" >&5
 echo $ECHO_N "checking for tgetnum in -lncurses... $ECHO_C" >&6
@@ -10788,7 +10869,7 @@ fi
 
     fi
 
-        LDFLAGS=${LDFLAGS_SAVE};
+        LDFLAGS=${LDFLAGS2_SAVE};
 
         if test -z "${rl_use}"; then
         echo "$as_me:$LINENO: result: MALOC was compiled with READLINE enabled" >&5
@@ -10802,6 +10883,7 @@ echo "$as_me: error: READLINE cannot be found!" >&2;}
 fi
 LDFLAGS=${LDFLAGS_SAVE};
 CPPFLAGS=${CPPFLAGS_SAVE};
+
 
 echo "$as_me:$LINENO: result: ---------- end configuring for MALOC linkage --------------" >&5
 echo "${ECHO_T}---------- end configuring for MALOC linkage --------------" >&6
@@ -11050,9 +11132,7 @@ else
   mc_found="";mc_lib=""
 fi
 
-        LDFLAGS_SAVE=${LDFLAGS};
-    CPPFLAGS_SAVE=${CPPFLAGS};
-    LDFLAGS=${mc_lib_path};
+        LDFLAGS=${mc_lib_path};
     CPPFLAGS=${mc_inc_path};
     mcx_found="";
     if test "${ac_cv_header_mcx_mcx_h+set}" = set; then
@@ -12608,8 +12688,9 @@ s,@EGREP@,$EGREP,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@py_path@,$py_path,;t t
 s,@PY_SHARED@,$PY_SHARED,;t t
-s,@PY_LDEXTRA@,$PY_LDEXTRA,;t t
+s,@PY_LDFLAGS@,$PY_LDFLAGS,;t t
 s,@PY_CFLAGS@,$PY_CFLAGS,;t t
+s,@PY_LINKFLAGS@,$PY_LINKFLAGS,;t t
 s,@PY_PRESENT_TRUE@,$PY_PRESENT_TRUE,;t t
 s,@PY_PRESENT_FALSE@,$PY_PRESENT_FALSE,;t t
 s,@math_lib@,$math_lib,;t t
