TJD:  Modified floating point error fix by using new VFLOOR macro.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3756,58 +3756,6 @@ echo "${ECHO_T}Disabling debugger compiler flags to avert OSF weirdness" >&6
 fi
 
 
-echo "$as_me:$LINENO: checking if the compiler creates floating point errors" >&5
-echo $ECHO_N "checking if the compiler creates floating point errors... $ECHO_C" >&6
-
-cat > fperror.c <<EOF
-    int main(){
-        double test, ofrac;
-        int value;
-        value = 28;
-        ofrac = 0.1;
-        test = (33/(1 + 2*ofrac) + 0.5);
-        if ((int)test != value){
-            printf("Ut oh!");
-        }
-        return 0;
-    }
-EOF
-ac_try='$CC -c $CFLAGS fperror.c 1>&5'
-if { (eval echo "$as_me:$LINENO: \"$actry\"") >&5
-  (eval $actry) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; then
-    $CC -o fperror.test $CFLAGS fperror.c
-    FPRESULTS=`./fperror.test`
-    if test -n "$FPRESULTS"; then
-        echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-        if test "${CC}" = "icc"; then
-            echo "Compiler causes floating point errors!" >&5
-            rm -f fperror*
-            echo "*** For icc add -mp to the CFLAGS environment variable. ***"
-        fi
-        { { echo "$as_me:$LINENO: error: Compiled floating point errors!" >&5
-echo "$as_me: error: Compiled floating point errors!" >&2;}
-   { (exit 1); exit 1; }; }
-    else
-        echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    fi
-else
-    echo "$as_me:$LINENO: result: unknown" >&5
-echo "${ECHO_T}unknown" >&6
-    echo "configure: failed program was:" >&5
-    cat fperror.c >&5
-    rm -f fperror*
-    { { echo "$as_me:$LINENO: error: failed to compile test C program" >&5
-echo "$as_me: error: failed to compile test C program" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-
 
 
 cat > noformain.c <<EOF
@@ -5797,7 +5745,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5800 "configure"' > conftest.$ac_ext
+  echo '#line 5748 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6326,7 +6274,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6329: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6277: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8158,7 +8106,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8161 "configure"
+#line 8109 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8256,7 +8204,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8259 "configure"
+#line 8207 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9826,6 +9774,72 @@ fi
 
 
 
+
+
+
+
+
+echo "$as_me:$LINENO: checking if the compiler creates floating point errors" >&5
+echo $ECHO_N "checking if the compiler creates floating point errors... $ECHO_C" >&6
+
+cat > fperror.c <<EOF
+    int main(){
+        double test, ofrac;
+        int value;
+        value = 28;
+        ofrac = 0.1;
+        test = (33/(1 + 2*ofrac) + 0.5);
+        if ((int)test != value){
+            printf("%.2E", 2*(value - test));
+        }
+        return 0;
+    }
+EOF
+actry='$CC -c $CFLAGS fperror.c 1>&5'
+if { (eval echo "$as_me:$LINENO: \"$actry\"") >&5
+  (eval $actry) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+    $CC -o fperror.test $CFLAGS fperror.c
+    FPRESULTS=`./fperror.test`
+    if test -n "$FPRESULTS"; then
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        echo "*** Warning: Compiler can cause floating point errors! ***"
+        if test "${CC}" = "icc"; then
+           echo "*** For icc add -mp flag if desired (see icc manual) ***"
+        fi
+
+cat >>confdefs.h <<\_ACEOF
+#define FLOAT_ERRORS 1
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define MACHINE_EPS $FPRESULTS
+_ACEOF
+
+    else
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define FLOAT_ERRORS 0
+_ACEOF
+
+    fi
+    rm -f fperror*
+else
+    echo "$as_me:$LINENO: result: unknown" >&5
+echo "${ECHO_T}unknown" >&6
+    echo "configure: failed program was:" >&5
+    cat fperror.c >&5
+    rm -f fperror*
+    { { echo "$as_me:$LINENO: error: failed to compile test C program" >&5
+echo "$as_me: error: failed to compile test C program" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
