Here's what works with FEM:
  test/reg-fem/noshell

Here's what doesn't work with FEM:

  bin/apbs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -469,7 +469,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os fetk_cpu_vendor_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE APBS_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 FLIBS CPP LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL math_lib liberty_lib nsl_lib socket_lib thread_lib maloc_lib maloc_inc mpi_lib mpi_inc mpi_bin rl_lib mcx_lib mcx_inc mc_lib mc_inc wall wall_pedantic wall_pedantic_ansi pedantic_ansi apbs_do_tools blas_lib blas_do_src arpack_lib arpack_do_tools lib_list inc_list LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os fetk_cpu_vendor_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE APBS_VERSION CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 FLIBS CPP LN_S ECHO RANLIB ac_ct_RANLIB EGREP LIBTOOL math_lib liberty_lib nsl_lib socket_lib thread_lib maloc_lib maloc_inc mpi_lib mpi_inc mpi_bin rl_lib mcx_lib mcx_inc mc_lib mc_inc wall wall_pedantic wall_pedantic_ansi pedantic_ansi apbs_do_tools blas_lib arpack_lib arpack_do_tools lib_list inc_list LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1037,7 +1037,6 @@ Optional Features:
   --disable-fetk          disable FEtk features
   --enable-pansi          enable pedantic ANSI compilation
   --disable-tools         disable tool compilation
-  --disable-blas          disable local BLAS compilation
   --disable-inline        disable inline functions (macros)
 
 Optional Packages:
@@ -1047,7 +1046,8 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects default=use both
   --with-mpiinc=PATH      directory containing <mpi.h>
   --with-mpilib=PATH      directory containing <libmpi.a>
-  --with-blas=PATH        link to user-specified BLAS (specify path to lib)
+  --with-blas=LDFLAGS     link to user-specified BLAS (specify flags to pass
+                          to ld)
   --with-arpack=PATH      enable ARPACK functions (specify path to lib)
 
 Some influential environment variables:
@@ -9602,7 +9602,7 @@ if test "${ac_cv_lib_maloc_maloc_link+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmaloc ${maloc_lib_path}-lmaloc ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
+LIBS="-lmaloc ${maloc_lib_path}-lmaloc -lvf2c ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -9651,7 +9651,7 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_maloc_maloc_link" >&5
 echo "${ECHO_T}$ac_cv_lib_maloc_maloc_link" >&6
 if test $ac_cv_lib_maloc_maloc_link = yes; then
-  maloc_found="yes";maloc_lib="${maloc_lib_path}-lmaloc"
+  maloc_found="yes";maloc_lib="${maloc_lib_path} -lmaloc -lvf2c"
 else
   maloc_found="";maloc_lib=""
 fi
@@ -9679,7 +9679,7 @@ if test "${ac_cv_lib_maloc_maloc_needs_mpi+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmaloc ${maloc_lib_path}-lmaloc ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
+LIBS="-lmaloc ${maloc_lib_path}-lmaloc -lvf2c ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -10087,7 +10087,7 @@ if test "${ac_cv_lib_maloc_maloc_needs_rl+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmaloc ${maloc_lib_path}-lmaloc ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
+LIBS="-lmaloc ${maloc_lib_path}-lmaloc -lvf2c ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -11031,53 +11031,185 @@ fi
 
 
 
-# Check whether --enable-blas or --disable-blas was given.
-if test "${enable_blas+set}" = set; then
-  enableval="$enable_blas"
-   disable_blas="yes"
-else
-   disable_blas=""
-
-fi;
-# BEGIN FETK LIBRARY/HEADER TEST BLOCK
-blas_do_src=""
 blas_lib=""
 
 # Check whether --with-blas or --without-blas was given.
 if test "${with_blas+set}" = set; then
   withval="$with_blas"
-   blas_lib="-lblas -L${withval}"
+   blas_lib="${withval}"
 else
    blas_lib=""
 
 fi;
-# INTERPRET THIS MESS
 echo "$as_me:$LINENO: checking for --with-blas" >&5
 echo $ECHO_N "checking for --with-blas... $ECHO_C" >&6
 if test -n "${blas_lib}"; then
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+
+    echo "$as_me:$LINENO: result: Looking for BLAS with ${CC} ${blas_lib}" >&5
+echo "${ECHO_T}Looking for BLAS with ${CC} ${blas_lib}" >&6
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    LDFLAGS_SAVE=${LDFLAGS};
+    CPPFLAGS_SAVE=${CPPFLAGS};
+    LDFLAGS=${blas_lib};
+    echo "$as_me:$LINENO: checking for dscal in -lblas" >&5
+echo $ECHO_N "checking for dscal in -lblas... $ECHO_C" >&6
+if test "${ac_cv_lib_blas_dscal+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lblas ${blas_lib} ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dscal ();
+int
+main ()
+{
+dscal ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_blas_dscal=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_blas_dscal=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_blas_dscal" >&5
+echo "${ECHO_T}$ac_cv_lib_blas_dscal" >&6
+if test $ac_cv_lib_blas_dscal = yes; then
+  blas_found="yes"
+else
+  blas_found=""
+fi
+
+    LDFLAGS=${LDFLAGS_SAVE};
+    CPPFLAGS=${CPPFLAGS_SAVE};
+    if test -z "${blas_found}"; then
+        { { echo "$as_me:$LINENO: error: BLAS libraries or headers missing:  exiting on error!" >&5
+echo "$as_me: error: BLAS libraries or headers missing:  exiting on error!" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
 else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-    echo "$as_me:$LINENO: checking for --disable-blas" >&5
-echo $ECHO_N "checking for --disable-blas... $ECHO_C" >&6
-    if test -n "${disable_blas}"; then
-       echo "$as_me:$LINENO: result: yes (you'd better have your own in LDFLAGS!)" >&5
-echo "${ECHO_T}yes (you'd better have your own in LDFLAGS!)" >&6
-    else
-       echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-       blas_do_src="blas"
+    blas_lib_path="${maloc_lib_path}"
+    blas_lib="${blas_lib_path} -lvf2c ${blas_lib_path} -lblas"
 
-cat >>confdefs.h <<\_ACEOF
-#define USE_PMG_BLAS
+    ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+    LDFLAGS_SAVE=${LDFLAGS};
+    CPPFLAGS_SAVE=${CPPFLAGS};
+    LDFLAGS=${blas_lib_path};
+    echo "$as_me:$LINENO: checking for dscal in -lblas" >&5
+echo $ECHO_N "checking for dscal in -lblas... $ECHO_C" >&6
+if test "${ac_cv_lib_blas_dscal+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lblas ${blas_lib} ${mpi_lib} ${rl_lib} ${liberty_lib} ${socket_lib} ${nsl_lib} ${math_lib} $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
 _ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-       blas_lib="../blas/libapbsblas.la"
-    fi
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dscal ();
+int
+main ()
+{
+dscal ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_blas_dscal=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_blas_dscal=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_blas_dscal" >&5
+echo "${ECHO_T}$ac_cv_lib_blas_dscal" >&6
+if test $ac_cv_lib_blas_dscal = yes; then
+  blas_found="yes"
+else
+  blas_found=""
 fi
 
+    LDFLAGS=${LDFLAGS_SAVE};
+    CPPFLAGS=${CPPFLAGS_SAVE};
+    if test -z "${blas_found}"; then
+        { { echo "$as_me:$LINENO: error: BLAS libraries or headers missing:  exiting on error!" >&5
+echo "$as_me: error: BLAS libraries or headers missing:  exiting on error!" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+fi
 
 
 echo "$as_me:$LINENO: checking for --with-arpack" >&5
@@ -11135,7 +11267,7 @@ echo "$as_me:$LINENO: result: ------------- end processing APBS configure option
 echo "${ECHO_T}------------- end processing APBS configure options -----------" >&6
 
 top_srcdir="`pwd`"
-lib_list="-L${top_srcdir}/lib ${mcx_lib} ${mc_lib} ${maloc_lib} ${thread_lib} ${mpi_lib} ${math_lib} ${rl_lib} ${socket_lib} ${nsl_lib}"
+lib_list="-L${top_srcdir}/lib ${mcx_lib} ${mc_lib} ${maloc_lib} ${blas_lib} ${thread_lib} ${mpi_lib} ${math_lib} ${rl_lib} ${socket_lib} ${nsl_lib}"
 inc_list="-I. ${maloc_inc} ${mc_inc} ${mcx_inc} ${mpi_inc}"
 
 
@@ -11885,7 +12017,6 @@ s,@wall_pedantic_ansi@,$wall_pedantic_ansi,;t t
 s,@pedantic_ansi@,$pedantic_ansi,;t t
 s,@apbs_do_tools@,$apbs_do_tools,;t t
 s,@blas_lib@,$blas_lib,;t t
-s,@blas_do_src@,$blas_do_src,;t t
 s,@arpack_lib@,$arpack_lib,;t t
 s,@arpack_do_tools@,$arpack_do_tools,;t t
 s,@lib_list@,$lib_list,;t t
