TJD:  Added autoconf check to look for floating point rounding errors - necessary since small errors can cause different grid spacings/# grid points/ results.  Configure dies if rounding errors found.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1482,7 +1482,11 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+# Add the stamp file to the list of files AC keeps track of,
+# along with our hook.
           ac_config_headers="$ac_config_headers src/aaa_inc/apbscfg.h"
+
+
 
 ac_aux_dir=
 for ac_dir in config $srcdir/config; do
@@ -3595,7 +3599,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3598:" \
+echo "$as_me:3602:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -3750,6 +3754,58 @@ echo "${ECHO_T}Disabling debugger compiler flags to avert OSF weirdness" >&6
      CXXFLAGS=`echo ${CXXFLAGS} | sed 's/-g//g'`;
   fi
 fi
+
+
+echo "$as_me:$LINENO: checking if the compiler creates floating point errors" >&5
+echo $ECHO_N "checking if the compiler creates floating point errors... $ECHO_C" >&6
+
+cat > fperror.c <<EOF
+    int main(){
+        double test, ofrac;
+        int value;
+        value = 28;
+        ofrac = 0.1;
+        test = (33/(1 + 2*ofrac) + 0.5);
+        if ((int)test != value){
+            printf("Ut oh!");
+        }
+        return 0;
+    }
+EOF
+ac_try='$CC -c $CFLAGS fperror.c 1>&5'
+if { (eval echo "$as_me:$LINENO: \"$actry\"") >&5
+  (eval $actry) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+    $CC -o fperror.test $CFLAGS fperror.c
+    FPRESULTS=`./fperror.test`
+    if test -n "$FPRESULTS"; then
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+        if test "${CC}" = "icc"; then
+            echo "Compiler causes floating point errors!" >&5
+            rm -f fperror*
+            echo "*** For icc add -mp to the CFLAGS environment variable. ***"
+        fi
+        { { echo "$as_me:$LINENO: error: Compiled floating point errors!" >&5
+echo "$as_me: error: Compiled floating point errors!" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+        echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    fi
+else
+    echo "$as_me:$LINENO: result: unknown" >&5
+echo "${ECHO_T}unknown" >&6
+    echo "configure: failed program was:" >&5
+    cat fperror.c >&5
+    rm -f fperror*
+    { { echo "$as_me:$LINENO: error: failed to compile test C program" >&5
+echo "$as_me: error: failed to compile test C program" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 
 
@@ -5741,7 +5797,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5744 "configure"' > conftest.$ac_ext
+  echo '#line 5800 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6270,7 +6326,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:6273: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:6329: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -8102,7 +8158,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8105 "configure"
+#line 8161 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8200,7 +8256,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8203 "configure"
+#line 8259 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13267,6 +13323,12 @@ echo X$ac_file |
   	  /^X\(\/\/\)$/{ s//\1/; q; }
   	  /^X\(\/\).*/{ s//\1/; q; }
   	  s/.*/./; q'`/stamp-h$_am_stamp_count
+  # Run the commands associated with the file.
+  case $ac_file in
+    src/aaa_inc/apbscfg.h ) # update the timestamp
+echo 'timestamp for src/aaa_inc/apbscfg.h' >"src/aaa_inc/stamp-h1"
+ ;;
+  esac
 done
 _ACEOF
 cat >>$CONFIG_STATUS <<\_ACEOF
