Added in OpenMPI support to APBS. Tested against OpenMPI 1.2.6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21889,29 +21889,84 @@ echo "$as_me: error: Error...Could not find LAM-MPI libraries in ${mpi_path}/lib
 		fi
 	fi
 
-#	if test -n "${USE_OPMI}"; then
-#		AC_CHECK_FILE(${mpi_path}/lib/libmpi.a, [HAS_MPI_LIB="yes"], [])
-#		AC_CHECK_FILE(${mpi_path}/lib/libmpi.so, [HAS_MPI_LIB="yes"], [])
-#		AC_CHECK_FILE(${mpi_path}/lib/liblam.dylib, [HAS_MPI_LIB="yes"], [])
-#		if test -n "${HAS_MPI_LIB}"; then
-#			mpi_lib="-L${mpi_path}/lib -lmpi"
-#		else
-#			AC_MSG_ERROR([Error...Could not find LAM-MPI libraries in ${mpi_path}/lib], 0)
-#		fi
-#	fi
-
-	USE_MPI="yes"
+	if test -n "${USE_OPMI}"; then
+		as_ac_File=`echo "ac_cv_file_${mpi_path}/lib/libmpi.a" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${mpi_path}/lib/libmpi.a" >&5
+echo $ECHO_N "checking for ${mpi_path}/lib/libmpi.a... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${mpi_path}/lib/libmpi.a"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAS_MPI_LIB="yes"
 fi
 
-if test -n "${USE_OPMI}"; then
-  	HAS_MPI_LIB="yes"
-	HAS_MPI_INC="yes"
-	mpi_inc=""
-	mpi_lib=""
+		as_ac_File=`echo "ac_cv_file_${mpi_path}/lib/libmpi.so" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${mpi_path}/lib/libmpi.so" >&5
+echo $ECHO_N "checking for ${mpi_path}/lib/libmpi.so... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${mpi_path}/lib/libmpi.so"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAS_MPI_LIB="yes"
+fi
 
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_MPI_H
-_ACEOF
+		as_ac_File=`echo "ac_cv_file_${mpi_path}/lib/libmpi.dylib" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${mpi_path}/lib/libmpi.dylib" >&5
+echo $ECHO_N "checking for ${mpi_path}/lib/libmpi.dylib... $ECHO_C" >&6; }
+if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "${mpi_path}/lib/libmpi.dylib"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+ac_res=`eval echo '${'$as_ac_File'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  HAS_MPI_LIB="yes"
+fi
+
+		if test -n "${HAS_MPI_LIB}"; then
+			mpi_lib="-L${mpi_path}/lib -lmpi"
+		else
+			{ { echo "$as_me:$LINENO: error: Error...Could not find LAM-MPI libraries in ${mpi_path}/lib" >&5
+echo "$as_me: error: Error...Could not find LAM-MPI libraries in ${mpi_path}/lib" >&2;}
+   { (exit 0); exit 0; }; }
+		fi
+	fi
 
 	USE_MPI="yes"
 fi
