TJD:  Made multiple mpi autoconf bug a little less likely (but still not completely fixed)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10370,62 +10370,10 @@ fi
     if test -n "${mpi_use}"; then
         echo "$as_me:$LINENO: result: Looking for MPI library with ${mpi_lib_path}..." >&5
 echo "${ECHO_T}Looking for MPI library with ${mpi_lib_path}..." >&6
-        echo "$as_me:$LINENO: checking for main in -lmpi" >&5
-echo $ECHO_N "checking for main in -lmpi... $ECHO_C" >&6
-if test "${ac_cv_lib_mpi_main+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmpi ${mpi_lib_path} $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
 
-
-int
-main ()
-{
-main ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_mpi_main=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_mpi_main=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_main" >&5
-echo "${ECHO_T}$ac_cv_lib_mpi_main" >&6
-if test $ac_cv_lib_mpi_main = yes; then
-  mpi_use="yes";mpi_lib="${mpi_lib_path}-lmpi";mpi_bin="pnoshell"
-else
-  mpi_use="";mpi_lib="";mpi_bin=""
-fi
-
-        if test -z "${mpi_use}"; then
-            echo "$as_me:$LINENO: checking for main in -lmpich" >&5
+        HAS_MPICH=`echo ${mpi_lib_path} | grep mpich`
+        if test -n "${HAS_MPICH}"; then
+           echo "$as_me:$LINENO: checking for main in -lmpich" >&5
 echo $ECHO_N "checking for main in -lmpich... $ECHO_C" >&6
 if test "${ac_cv_lib_mpich_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -10479,6 +10427,174 @@ else
   mpi_use="";mpi_lib=""
 fi
 
+           if test -z "${mpi_use}"; then
+             echo "$as_me:$LINENO: checking for main in -lmpi" >&5
+echo $ECHO_N "checking for main in -lmpi... $ECHO_C" >&6
+if test "${ac_cv_lib_mpi_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpi ${mpi_lib_path} $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpi_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpi_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mpi_main" >&6
+if test $ac_cv_lib_mpi_main = yes; then
+  mpi_use="yes";mpi_lib="${mpi_lib_path}-lmpi";mpi_bin="pnoshell"
+else
+  mpi_use="";mpi_lib="";mpi_bin=""
+fi
+
+           fi
+
+        else
+           echo "$as_me:$LINENO: checking for main in -lmpi" >&5
+echo $ECHO_N "checking for main in -lmpi... $ECHO_C" >&6
+if test "${ac_cv_lib_mpi_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpi ${mpi_lib_path} $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpi_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpi_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mpi_main" >&6
+if test $ac_cv_lib_mpi_main = yes; then
+  mpi_use="yes";mpi_lib="${mpi_lib_path}-lmpi";mpi_bin="pnoshell"
+else
+  mpi_use="";mpi_lib="";mpi_bin=""
+fi
+
+           if test -z "${mpi_use}"; then
+              echo "$as_me:$LINENO: checking for main in -lmpich" >&5
+echo $ECHO_N "checking for main in -lmpich... $ECHO_C" >&6
+if test "${ac_cv_lib_mpich_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpich ${mpi_lib_path} $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpich_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpich_main=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpich_main" >&5
+echo "${ECHO_T}$ac_cv_lib_mpich_main" >&6
+if test $ac_cv_lib_mpich_main = yes; then
+  mpi_use="yes";mpi_lib="${mpi_lib_path}-lmpich"
+else
+  mpi_use="";mpi_lib=""
+fi
+
+           fi
         fi
     fi
     if test -z "${mpi_use}"; then
